/* eslint-disable react/require-default-props */
import {
  Paper, Text, Stack, Grid, Image, Box, Badge,
} from '@mantine/core';
import { formatCurrency } from '@/utils/currency';

export interface ExportProduct {
  id: string;
  name: string;
  description?: string | null;
  priceUSD: number;
  priceSYP?: number | null;
  imageUrls?: string[] | null;
  category?: string | null;
}

interface CatalogTemplateProps {
  products: ExportProduct[];
  merchantName: string;
  watermark?: boolean;
}

export function CatalogTemplate({ products, merchantName, watermark }: CatalogTemplateProps) {
  return (
    <Paper p="xl" bg="white" style={{ width: '100%', minHeight: 400 }}>
      <Stack gap="lg">
        <Text fw={700} size="2rem" ta="center" style={{ letterSpacing: -1 }}>
          {merchantName}
        </Text>
        <Text size="sm" c="dimmed" ta="center">
          Product Catalog
        </Text>

        <Grid gutter="md">
          {products.map((product) => (
            <Grid.Col key={product.id} span={{ base: 12, sm: 6, md: 4 }}>
              <Paper
                p="sm"
                withBorder
                style={{ height: '100%' }}
              >
                <Stack gap="xs">
                  {product.imageUrls && product.imageUrls.length > 0 ? (
                    <Image
                      src={product.imageUrls[0]}
                      alt={product.name}
                      w="100%"
                      h={120}
                      radius="sm"
                      fit="cover"
                    />
                  ) : (
                    <Box
                      style={{
                        width: '100%',
                        height: 120,
                        backgroundColor: '#f5f5f5',
                        borderRadius: 4,
                      }}
                    />
                  )}
                  <Box>
                    <Text fw={600} size="sm" lineClamp={1}>
                      {product.name}
                    </Text>
                    {product.category && (
                      <Badge size="xs" variant="outline" mt={2}>
                        {product.category}
                      </Badge>
                    )}
                    <Text size="xs" c="dimmed" mt={4} lineClamp={2}>
                      {product.description || 'No description'}
                    </Text>
                  </Box>
                  <Box>
                    <Text fw={700} size="md" c="blue">
                      {formatCurrency(product.priceUSD, 'USD')}
                    </Text>
                    {product.priceSYP && (
                      <Text size="xs" c="dimmed">
                        {formatCurrency(product.priceSYP, 'SYP')}
                      </Text>
                    )}
                  </Box>
                </Stack>
              </Paper>
            </Grid.Col>
          ))}
        </Grid>

        {watermark && (
          <Text size="xs" c="dimmed" ta="center">
            Catalog generated by MerchantHub
          </Text>
        )}
      </Stack>
    </Paper>
  );
}
