/* eslint-disable react/require-default-props */
import {
  Paper, Text, Stack, Box, Table, Badge,
} from '@mantine/core';
import { formatCurrency } from '@/utils/currency';

export interface ExportProduct {
  id: string;
  name: string;
  description?: string | null;
  priceUSD: number;
  priceSYP?: number | null;
  imageUrls?: string[] | null;
  category?: string | null;
}

interface PriceListTemplateProps {
  products: ExportProduct[];
  merchantName: string;
  watermark?: boolean;
}

export function PriceListTemplate({ products, merchantName, watermark }: PriceListTemplateProps) {
  return (
    <Paper p="xl" bg="white" style={{ width: '100%', minHeight: 400 }}>
      <Stack gap="lg">
        <Box ta="center">
          <Text fw={700} size="xl">
            {merchantName}
          </Text>
          <Text size="sm" c="dimmed">
            Price List
          </Text>
        </Box>

        <Box style={{ border: '2px solid #333', borderRadius: 4 }}>
          <Table striped highlightOnHover>
            <Table.Thead>
              <Table.Tr style={{ backgroundColor: '#333', color: 'white' }}>
                <Table.Th style={{ color: 'white', padding: '12px 16px' }}>Product</Table.Th>
                <Table.Th style={{ color: 'white', padding: '12px 16px' }}>Category</Table.Th>
                <Table.Th style={{ color: 'white', textAlign: 'right', padding: '12px 16px' }}>USD</Table.Th>
                <Table.Th style={{ color: 'white', textAlign: 'right', padding: '12px 16px' }}>SYP</Table.Th>
              </Table.Tr>
            </Table.Thead>
            <Table.Tbody>
              {products.map((product, index) => (
                <Table.Tr
                  key={product.id}
                  style={{ backgroundColor: index % 2 === 0 ? '#fff' : '#f8f9fa' }}
                >
                  <Table.Td style={{ padding: '10px 16px' }}>
                    <Text fw={500}>{product.name}</Text>
                  </Table.Td>
                  <Table.Td style={{ padding: '10px 16px' }}>
                    {product.category && (
                      <Badge size="sm" variant="light">
                        {product.category}
                      </Badge>
                    )}
                  </Table.Td>
                  <Table.Td style={{ padding: '10px 16px', textAlign: 'right', fontWeight: 600 }}>
                    {formatCurrency(product.priceUSD, 'USD')}
                  </Table.Td>
                  <Table.Td style={{ padding: '10px 16px', textAlign: 'right', color: '#666' }}>
                    {product.priceSYP ? formatCurrency(product.priceSYP, 'SYP') : '-'}
                  </Table.Td>
                </Table.Tr>
              ))}
            </Table.Tbody>
          </Table>
        </Box>

        <Box style={{ borderTop: '1px solid #e0e0e0', paddingTop: 16 }}>
          <Text size="xs" c="dimmed" ta="center">
            Prices subject to change. Contact us for latest pricing.
          </Text>
        </Box>

        {watermark && (
          <Text size="xs" c="dimmed" ta="center">
            Price list generated by MerchantHub
          </Text>
        )}
      </Stack>
    </Paper>
  );
}
